from marshmallow import Schema, fields
class LeadsSchema(Schema):
    name = fields.Str()
    cell = fields.Str()
    email = fields.Email()
    created_date = fields.Str()
    created_time = fields.Str()
    vehicle = fields.Str()
    primary_sales_person = fields.Str()
    last_date_of_contact = fields.Str()
    last_date_of_contact_time = fields.Str()
    number_of_times_sales_person_contacted = fields.Int()
    number_of_times_customer_contacted = fields.Int()
    pending_replies = fields.Boolean()
    pending_replies_text = fields.Str()
    avg_daily_contacted = fields.Float()
    sales_status = fields.Str()
    up_type = fields.Str()
    source = fields.Str()
    sub_source = fields.Str()
    lead_url = fields.Str()

class UserSchema(Schema):
    name = fields.Str()
    username = fields.Str()
    password = fields.Str()
    threads = fields.List(fields.Dict())
    profile_image = fields.Str()
    todays_emails = fields.Int()
    todays_texts = fields.Int()
    total_leads = fields.Int()
    leads_table_data = fields.Nested(LeadsSchema, many=True)